// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADmzQvtlB3dVLBV1--DBJkQN9pg4Nk7RA',
    appId: '1:391111389156:web:8dc9d020359cc0ff5021f1',
    messagingSenderId: '391111389156',
    projectId: 'propersona-dev-huzentra',
    authDomain: 'propersona-dev-huzentra.firebaseapp.com',
    storageBucket: 'propersona-dev-huzentra.firebasestorage.app',
    measurementId: 'G-4NQD34R3WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxXqE4UZmDpJWf8Fv1YaSADTgSefBKYXo',
    appId: '1:391111389156:android:0b2960b43738a24d5021f1',
    messagingSenderId: '391111389156',
    projectId: 'propersona-dev-huzentra',
    storageBucket: 'propersona-dev-huzentra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Y2oFeYhMjn3gFNbY4mvvCabdDU4mp-8',
    appId: '1:391111389156:ios:2e43cc7ab74165815021f1',
    messagingSenderId: '391111389156',
    projectId: 'propersona-dev-huzentra',
    storageBucket: 'propersona-dev-huzentra.firebasestorage.app',
    iosBundleId: 'com.huzentra.proPersona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Y2oFeYhMjn3gFNbY4mvvCabdDU4mp-8',
    appId: '1:391111389156:ios:2e43cc7ab74165815021f1',
    messagingSenderId: '391111389156',
    projectId: 'propersona-dev-huzentra',
    storageBucket: 'propersona-dev-huzentra.firebasestorage.app',
    iosBundleId: 'com.huzentra.proPersona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADmzQvtlB3dVLBV1--DBJkQN9pg4Nk7RA',
    appId: '1:391111389156:web:a58a8464c46aea6a5021f1',
    messagingSenderId: '391111389156',
    projectId: 'propersona-dev-huzentra',
    authDomain: 'propersona-dev-huzentra.firebaseapp.com',
    storageBucket: 'propersona-dev-huzentra.firebasestorage.app',
    measurementId: 'G-PHK1WNQS50',
  );
}
