// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgnEXM3GwOkNV3uLidMSlJkcR8bwt6ZU',
    appId: '1:402121786712:web:0d5a6ac8618623db0ed12d',
    messagingSenderId: '402121786712',
    projectId: 'propersona-prod-huzentra',
    authDomain: 'propersona-prod-huzentra.firebaseapp.com',
    storageBucket: 'propersona-prod-huzentra.firebasestorage.app',
    measurementId: 'G-F7EW3T3DP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwjAaJwpszqDD-SYc-LsGiLYAubxoMF6o',
    appId: '1:402121786712:android:6d4534c763d97bbe0ed12d',
    messagingSenderId: '402121786712',
    projectId: 'propersona-prod-huzentra',
    storageBucket: 'propersona-prod-huzentra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCSJ3Dy1FDudtxIpiWgO9nkEqyn6T7VQ',
    appId: '1:402121786712:ios:94e85623243c6d9d0ed12d',
    messagingSenderId: '402121786712',
    projectId: 'propersona-prod-huzentra',
    storageBucket: 'propersona-prod-huzentra.firebasestorage.app',
    iosBundleId: 'com.huzentra.proPersona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCSJ3Dy1FDudtxIpiWgO9nkEqyn6T7VQ',
    appId: '1:402121786712:ios:94e85623243c6d9d0ed12d',
    messagingSenderId: '402121786712',
    projectId: 'propersona-prod-huzentra',
    storageBucket: 'propersona-prod-huzentra.firebasestorage.app',
    iosBundleId: 'com.huzentra.proPersona',
  );
}
